# Generated by Django 5.2.7 on 2025-11-04 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_detect_language", models.BooleanField(default=True)),
                (
                    "default_language",
                    models.CharField(
                        choices=[("en", "English"), ("sv", "Swedish")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "notification_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("escalation_threshold", models.PositiveSmallIntegerField(default=3)),
                (
                    "widget_title",
                    models.CharField(
                        blank=True, default="Safelift AI Assistant", max_length=120
                    ),
                ),
                ("welcome_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_system_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_settings",
            },
        ),
    ]
